//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.312
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConquistadorGame.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ConquistadorGame.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap BigDie1 {
            get {
                object obj = ResourceManager.GetObject("BigDie1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BigDie2 {
            get {
                object obj = ResourceManager.GetObject("BigDie2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BigDie3 {
            get {
                object obj = ResourceManager.GetObject("BigDie3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BigDie4 {
            get {
                object obj = ResourceManager.GetObject("BigDie4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BigDie5 {
            get {
                object obj = ResourceManager.GetObject("BigDie5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap BigDie6 {
            get {
                object obj = ResourceManager.GetObject("BigDie6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream CountrySelect {
            get {
                return ResourceManager.GetStream("CountrySelect", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream CountrySelectError {
            get {
                return ResourceManager.GetStream("CountrySelectError", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream DiceRoll {
            get {
                return ResourceManager.GetStream("DiceRoll", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream DiceRollFailure {
            get {
                return ResourceManager.GetStream("DiceRollFailure", resourceCulture);
            }
        }
        
        internal static System.IO.UnmanagedMemoryStream DiceRollSuccess {
            get {
                return ResourceManager.GetStream("DiceRollSuccess", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap SmallDie1 {
            get {
                object obj = ResourceManager.GetObject("SmallDie1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmallDie2 {
            get {
                object obj = ResourceManager.GetObject("SmallDie2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmallDie3 {
            get {
                object obj = ResourceManager.GetObject("SmallDie3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmallDie4 {
            get {
                object obj = ResourceManager.GetObject("SmallDie4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmallDie5 {
            get {
                object obj = ResourceManager.GetObject("SmallDie5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap SmallDie6 {
            get {
                object obj = ResourceManager.GetObject("SmallDie6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
